### ISSUE TITLE
Issue with Parallelism

### ISSUE THREAD

**Issue by shadab005** [AntoineAugusti/go-exercices#3]
https://github.com/AntoineAugusti/go-exercices/blob/f28113ebe9f41e12a6ea80da08dbc6d484f1763a/12-exercise-web-crawler.go#L50
```
for _, childrenUrl := range urls {
		go CrawlRecursive(childrenUrl, depth-1, fetcher, childrenQuit, visitedUrls)
		// To exit goroutines. This channel will always be filled
		<-childrenQuit
	}
```
This loop is not executing in parallel.  Only one crawlRecursive will be called and other has to wait due to <-childrenQuit.
So it seems like code is executing sequentially rather than parallel.

Let me know if you think otherwise.

**Comment by developerdong** [comment]
I think @shadab005 is right, I found the same error, while @shadab005 has already created an issue before.

**Comment by adrixo** [comment]
As far as I understand, also a mutex is need in order to write/read from the to avoid multiple crawl on same webpage by several threads

**Comment by elenacliu** [comment]
yes, I also agree with @shadab005
and a code example similar with that can be found on: https://go.dev/doc/effective_go#parallel
